resolver: lts-8.5
packages:
- '.'
extra-deps: []
flags: {}
extra-package-dbs: []
ghc-options:
  "*": -Wall
  "TFWH":  -fforce-recomp -threaded -rtsopts -with-rtsopts=-N
rebuild-ghc-options: true

build:
  library-profiling: false
  executable-profiling: false

  haddock: true
  open-haddocks: true

  test: true
